# World Cup Database Players

A ideia aqui vai ser tirar algumas estatisticas e brincar com a base de dados

In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "wc2018-players.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "djamshed/fifa-world-cup-2018-players",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_155801/2813532655.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:         Team   # Pos.   FIFA Popular Name  Birth Date  Shirt Name  \
0  Argentina   3   DF  TAGLIAFICO Nicolas  31.08.1992  TAGLIAFICO
1  Argentina  22   MF      PAVON Cristian  21.01.1996       PAVÓN
2  Argentina  15   MF      LANZINI Manuel  15.02.1993     LANZINI
3  Argentina  18   DF      SALVIO Eduardo  13.07.1990      SALVIO
4  Argentina  10   FW        MESSI Lionel  24.06.1987       MESSI

                       Club  Height  Weight
0            AFC Ajax (NED)     169      65
1     CA Boca Juniors (ARG)     169      65
2  West Ham United FC (ENG)     167      66
3          SL Benfica (POR)     167      69
4        FC Barcelona (ESP)     170      72

Transformação da base de dados para o pandas

In [2]:
df.rename(columns={'Pos.': 'Position'}, inplace=True)
df

,Team,#,Position,FIFA Popular Name,Birth Date,Shirt Name,Club,Height,Weight
0,Argentina,3,DF,TAGLIAFICO Nicolas,31.08.1992,TAGLIAFICO,AFC Ajax (NED),169,65
1,Argentina,22,MF,PAVON Cristian,21.01.1996,PAVÓN,CA Boca Juniors (ARG),169,65
2,Argentina,15,MF,LANZINI Manuel,15.02.1993,LANZINI,West Ham United FC (ENG),167,66
3,Argentina,18,DF,SALVIO Eduardo,13.07.1990,SALVIO,SL Benfica (POR),167,69
4,Argentina,10,FW,MESSI Lionel,24.06.1987,MESSI,FC Barcelona (ESP),170,72
...,...,...,...,...,...,...,...,...,...
731,Uruguay,15,MF,VECINO Matias,24.08.1991,VECINO,FC Internazionale (ITA),189,80
732,Uruguay,23,GK,SILVA Martin,25.03.1983,M. SILVA,CR Vasco da Gama (BRA),187,82
733,Uruguay,9,FW,SUAREZ Luis,24.01.1987,SUAREZ,FC Barcelona (ESP),182,85
734,Uruguay,18,FW,GOMEZ Maximiliano,14.08.1996,M. GOMEZ,Celta Vigo (ESP),186,85
735,Uruguay,19,DF,COATES Sebastian,07.10.1990,COATES,Sporting CP (POR),196,89

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Team               736 non-null    object
 1   #                  736 non-null    int64
 2   Position           736 non-null    object
 3   FIFA Popular Name  736 non-null    object
 4   Birth Date         736 non-null    object
 5   Shirt Name         736 non-null    object
 6   Club               736 non-null    object
 7   Height             736 non-null    int64
 8   Weight             736 non-null    int64
dtypes: int64(3), object(6)
memory usage: 51.9+ KB

In [4]:
df_age = df #cria um df para mexer na idade

In [6]:
from datetime import datetime

def calcular_idade(birth_date_str):
    # Converte a string para data
    birth_date = datetime.strptime(birth_date_str, "%d.%m.%Y")
    # Data de referência: junho de 2018
    ref_date = datetime(2018, 6, 1)
    # Calcula idade
    idade = ref_date.year - birth_date.year - ((ref_date.month, ref_date.day) < (birth_date.month, birth_date.day))
    return idade

df_age['Age'] = df_age['Birth Date'].apply(calcular_idade)
df_age.head()

,Team,#,Position,FIFA Popular Name,Birth Date,Shirt Name,Club,Height,Weight,Age
0,Argentina,3,DF,TAGLIAFICO Nicolas,31.08.1992,TAGLIAFICO,AFC Ajax (NED),169,65,25
1,Argentina,22,MF,PAVON Cristian,21.01.1996,PAVÓN,CA Boca Juniors (ARG),169,65,22
2,Argentina,15,MF,LANZINI Manuel,15.02.1993,LANZINI,West Ham United FC (ENG),167,66,25
3,Argentina,18,DF,SALVIO Eduardo,13.07.1990,SALVIO,SL Benfica (POR),167,69,27
4,Argentina,10,FW,MESSI Lionel,24.06.1987,MESSI,FC Barcelona (ESP),170,72,30

In [7]:
df_age.describe()

               #      Height      Weight         Age
count  736.00000  736.000000  736.000000  736.000000
mean    12.00000  182.407609   77.188859   27.387228
std      6.63776    6.930924    7.233778    3.932879
min      1.00000  165.000000   59.000000   19.000000
25%      6.00000  178.000000   72.000000   25.000000
50%     12.00000  183.000000   77.000000   27.000000
75%     18.00000  187.000000   82.000000   30.000000
max     23.00000  201.000000   99.000000   45.000000

In [8]:
df_age.describe(include=['object'])

,Team,Position,FIFA Popular Name,Birth Date,Shirt Name,Club
count,736,736,736,736,736,736
unique,32,4,735,679,729,310
top,Argentina,DF,SANCHEZ Carlos,25.02.1990,RODRIGUEZ,Manchester City FC (ENG)
freq,23,248,2,3,3,16

In [9]:
import pandas as pd

In [ ]:
df_gols = pd.read_csv("World_cup_2018_goals.csv")

In [11]:
df_gols.head()

,Date,Stage,Home,Away,Team_scored,Player_scored,Time,Own_goal,Penalty
0,2018-06-14,Group-1,Russia,Saudi Arabia,Russia,Yury Gazinksky,12,N,N
1,2018-06-14,Group-1,Russia,Saudi Arabia,Russia,Denis Cheryshev,43,N,N
2,2018-06-14,Group-1,Russia,Saudi Arabia,Russia,Denis Cheryshev,90+1,N,N
3,2018-06-14,Group-1,Russia,Saudi Arabia,Russia,Artem Dzyuba,71,N,N
4,2018-06-14,Group-1,Russia,Saudi Arabia,Russia,Aleksandr Golovin,90+4,N,N

In [13]:
df_gols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           169 non-null    object
 1   Stage          169 non-null    object
 2   Home           169 non-null    object
 3   Away           169 non-null    object
 4   Team_scored    169 non-null    object
 5   Player_scored  169 non-null    object
 6   Time           169 non-null    object
 7   Own_goal       169 non-null    object
 8   Penalty        169 non-null    object
dtypes: object(9)
memory usage: 12.0+ KB